name: "OpenAPI Diff Action"
description: "Compare two OpenAPI specs to determine if the newer spec is a major update (breaking changes), minor update (non-breaking changes only), or a patch (no changes)"

inputs:
  head-spec-path:
    description: "The relative path to the HEAD (new) spec"
    required: true
  base-spec-path:
    description: "The relative path to the BASE (old) spec"
    required: true
  label-on-pr:
    description: "Add a label to the pull request with the semver-compatible type of change detected; possible values: 'major', 'minor', 'patch' (default: true)"
    required: false
    default: "true"
  comment-on-pr:
    description: "Add or update a comment to the pull request with information about the detected differences (default: true)"
    required: false
    default: "true"
  warn-on-deprecated-removal:
    description: "If the only detected breaking differences are the removal of deprecated elements, adds a warning annotation to the build and avoid failing the build if 'fail-on-breaking' is true (default: true)"
    required: false
    default: "true"
  fail-on-breaking-differences:
    description: "Fail the build if breaking differences are detected (default: true)"
    required: false
    default: "true"

outputs:
  change-type:
    description: "The semver-compatible type of change detected; possible values: 'major', 'minor', 'patch'"
  has-changes:
    description: "Whether or not the HEAD spec introduces any changes at all"
  has-breaking-differences:
    description: "Whether or not the HEAD spec introduces breaking differences"
  has-non-breaking-differences:
    description: "Whether or not the HEAD spec introduces non-breaking differences"

runs:
  using: "node12"
  main: "index.js"
