name: 'OpenAPI Diff Action'
description: 'Compare two OpenAPI specs to determine if the newer spec is a major update (breaking changes), minor update (non-breaking changes only), or a patch (no changes)'

inputs:
  head-spec:
    description: 'The relative path or http url of the HEAD (new) spec'
    required: true
  base-spec:
    description: 'The relative path or http url of the BASE (old) spec'
    required: true
  pull-request:
    description: 'The relevant pull request number'
    required: false
  add-label-to-pull-request:
    description: "Add a label to the pull request with the semver-compatible type of change detected; possible values: 'major', 'minor', 'patch' (default: true)"
    required: true
    default: 'true'
  add-comment-to-pull-request:
    description: 'Add or update a comment to the pull request with information about the detected changes (default: true)'
    required: true
    default: 'true'

outputs:
  classification:
    description: "The type of change detected; possible values: 'major', 'minor', 'patch'"

runs:
  using: docker
  image: Dockerfile
