name: 'OpenAPI Diff Action'
description: 'Compare two OpenAPI specs to determine if the newer spec is a major update (breaking changes), minor update (non-breaking changes only), or a patch (no changes)'

outputs:
  change-type:
    description: "The semver-compatible type of change detected; possible values: 'major', 'minor', 'patch'"
  has-changes:
    description: 'Whether or not the HEAD spec introduces any changes at all'
  has-breaking-differences:
    description: 'Whether or not the HEAD spec introduces breaking changes'
  has-non-breaking-differences:
    description: 'Whether or not the HEAD spec introduces non-breaking changes'

runs:
  using: docker
  image: Dockerfile
