name: 'OpenAPI Diff Action'
description: 'Compare two OpenAPI specs to determine if the newer spec is a major update (breaking changes), minor update (non-breaking changes only), or a patch (no changes)'

inputs:
  head:
    description: 'The relative path to the HEAD (new) spec'
    required: true
  base:
    description: 'The relative path to the BASE (old) spec'
    required: true
  label-on-pr:
    description: "Add a label to the pull request with the semver-compatible type of change detected; possible values: 'major', 'minor', 'patch' (default: true)"
    required: false
    default: 'true'
  comment-on-pr:
    description: 'Add or update a comment to the pull request with information about the detected changes (default: true)'
    required: false
    default: 'true'
  warn-on-deprecated-removal:
    description: 'Indicates that the removal of deprecated elements should issue a warning rather than an error (default: true)'
    required: false
    default: 'true'

outputs:
  change-type:
    description: "The semver-compatible type of change detected; possible values: 'major', 'minor', 'patch'"
  has-changes:
    description: 'Whether or not the HEAD spec introduces any changes at all'
  has-breaking-differences:
    description: 'Whether or not the HEAD spec introduces breaking changes'
  has-non-breaking-differences:
    description: 'Whether or not the HEAD spec introduces non-breaking changes'

runs:
  using: 'node12'
  main: 'dist/bundle.js'
