name: openapi-diff-test

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          HEAD_SPEC: test/head.yaml
          BASE_SPEC: test/base.yaml
          PULL_REQUEST: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ github.token }}
