name: openapi-diff-test

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          head-spec: test/head.yaml
          base-spec: test/base.yaml
