name: openapi-diff-test

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          head-spec: test/head.yaml
          base-spec: test/base.yaml
          pull-request: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
